### PR TITLE
using OS version of the 'unzip' command to unzip (instead of 'unzip' npm...

### PR DESCRIPTION
**Pull request by DavidBruant**
... module)

### CODE REVIEW

**Comment by DavidBruant** [comment]
Don't merge for now. 
@iOiurson @vallettea one of you should try it on your machine to see if it solves the problem of freezing big files.
Report your results. Merge if everything seems to work.

**Comment by vallettea** [comment]
@iOiurson did you tried ?

**Comment by vallettea** [comment]
No doesn't extract anything:

```
vallette@Mac-5 ~/Desktop/city-core (unzip-into-darkness)$ node tools/unzipCUB3ds.js --out /Users/vallette/Desktop/test --zip  /Users/vallette/Desktop/BATI3D_NT.zip
/Users/vallette/Desktop/BATI3D_NT.zip /Users/vallette/Desktop/test
csvParse 379165
extract: 121ms
nb of objects 0
all: 125ms
```

**Comment by DavidBruant** [comment]
Didn't find out to do that in OSX. Will figure it out another time.

**Pull request merged**
